### ISSUE TITLE
NullPointerException in BACnetUtils.dottedStringToBytes IF openvpn is running

### ISSUE THREAD

**Issue by jtakacs** [Frozenlock/wacnet#1]
I have downloaded wacnet 1.1.8, 1.1.7, 1.1.6 and 1.1.5, all of them gave me a similar exception right after starting the application. 

Is it possible to start this application without any BACnet traffic on the local network?

java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

java -jar wacnet-1.1.8-standalone.jar 
Exception in thread "main" java.lang.NullPointerException
        at com.serotonin.bacnet4j.base.BACnetUtils.dottedStringToBytes(BACnetUtils.java:92)
        at com.serotonin.bacnet4j.npdu.ip.IpNetwork.initialize(IpNetwork.java:129)
        at com.serotonin.bacnet4j.transport.Transport.initialize(Transport.java:121)
        at com.serotonin.bacnet4j.LocalDevice.initialize(LocalDevice.java:214)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
        at bacure.local_device$initialize$fn__3214.invoke(local_device.clj:170)
        at bacure.local_device$initialize.invoke(local_device.clj:170)
        at bacure.local_device$reset_local_device.invoke(local_device.clj:256)
        at bacure.local_device$load_local_device_backup.doInvoke(local_device.clj:277)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at bacure.core$boot_up.doInvoke(core.clj:11)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at wacnet.local_device$initialize.invoke(local_device.clj:12)
        at wacnet.local_device$initialize_with_exit_on_fail_BANG_.invoke(local_device.clj:36)
        at wacnet.server$_main.doInvoke(server.clj:31)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at wacnet.server.main(Unknown Source)

**Comment by jtakacs** [comment]
Update: I also tried running it with an older jvm:

 /usr/lib/jvm/java-6-oracle/bin/java -jar wacnet-1.1.8-standalone.jar 
Exception in thread "main" java.lang.NullPointerException
        at com.serotonin.bacnet4j.base.BACnetUtils.dottedStringToBytes(BACnetUtils.java:92)
        at com.serotonin.bacnet4j.npdu.ip.IpNetwork.initialize(IpNetwork.java:129)
        at com.serotonin.bacnet4j.transport.Transport.initialize(Transport.java:121)
        at com.serotonin.bacnet4j.LocalDevice.initialize(LocalDevice.java:214)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
        at bacure.local_device$initialize$fn__3214.invoke(local_device.clj:170)
        at bacure.local_device$initialize.invoke(local_device.clj:170)
        at bacure.local_device$reset_local_device.invoke(local_device.clj:256)
        at bacure.local_device$load_local_device_backup.doInvoke(local_device.clj:277)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at bacure.core$boot_up.doInvoke(core.clj:11)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at wacnet.local_device$initialize.invoke(local_device.clj:12)
        at wacnet.local_device$initialize_with_exit_on_fail_BANG_.invoke(local_device.clj:36)
        at wacnet.server$_main.doInvoke(server.clj:31)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at wacnet.server.main(Unknown Source)

**Comment by Frozenlock** [comment]
> Is it possible to start this application without any BACnet traffic on the local network?

Yes, but you won't see anything exciting... 

It seems wacnet can't initialize the local device and has some problems getting your computer interface.

What is your OS?

Did you modify any default configuration?

**Comment by jtakacs** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.10
Release:        14.10
Codename:       utopic

To be honest, I have modified my OS a few times, as the current project required it, but I mostly develop java applications, and every other java project runs just fine. Also the jdk is an unmodified version straight from Oracle.
I have not modified anything inside the wacnet.jar.

**Comment by Frozenlock** [comment]
Weird, Ubuntu is what I mostly use.

There isn't any configuration file in the wacnet directory, right?

Could you post the result of running:

``` bash
ifconfig -a
```

**Comment by jtakacs** [comment]
eth0      Link encap:Ethernet  HWaddr 54:ee:75:2c:0d:99  
          inet addr:192.168.200.42  Bcast:192.168.201.255  Mask:255.255.254.0
          inet6 addr: fe80::56ee:75ff:fe2c:d99/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1279057 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1665161 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1210050083 (1.2 GB)  TX bytes:1465968680 (1.4 GB)
          Interrupt:20 Memory:e1600000-e1620000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:139183936 errors:0 dropped:0 overruns:0 frame:0
          TX packets:139183936 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:7986921718 (7.9 GB)  TX bytes:7986921718 (7.9 GB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.8.150.3  P-t-P:10.8.150.3  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr e8:b1:fc:48:68:4a  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

Aaaand the winner is: openvpn.
After /etc/init.d/openvpn stop; wacet started without any problem, I can use the web interface.

**Comment by Frozenlock** [comment]
Thanks for reporting this, I'll see if I can put some kind of protection.

**Comment by jtakacs** [comment]
Your welcome. Thanks for the quick reply.
